### PR TITLE
UT for app/layout.tsx and app/page.tsx

### PR DESCRIPTION
**Pull request by Unknown-0perator**
I got a warning in terminal, couldn't able to solve it
console.error
      Warning: validateDOMNesting(...): <html> cannot appear as a child of <div>.
          at html
          at children (D:\OPENBC\openbc-web\src\app\layout.tsx:9:38)

      21 | describe('RootLayout', () => {
      22 |   it('renders without crashing', () => {
    > 23 |     render(<RootLayout />);
         |           ^
      24 |   });
      25 |
      26 |   it('renders Header and Footer components', () => {

### CODE REVIEW

**Comment by nam-m** [comment]
It's because RootLayout contains <html> tag, which is the whole page.
You probably won't need to test `render` the whole page

**Comment by nam-m** [comment]
I found this
https://www.reddit.com/r/nextjs/comments/17ysp6r/how_to_write_a_test_for_the_main_layout_file/

**Comment by Unknown-0perator** [comment]
> It's because RootLayout contains html tag, which is the whole page. You probably won't need to test `render` the whole page
Thanks @nam-m 
Most people don't suggest UT fo> It's because RootLayout contains html tag, which is the whole page. You probably won't need to test `render` the whole page
Thanks @nam-m 
Most people don't suggest UT for main layout, and also need render for testing `{childern}`.
I couldn't find any better solution, either we ignore the warning or remove ut for layoutr main layout, and also need render for testing `{childern}`.
I couldn't find any better solution, either we ignore the warning or remove ut for layout

**Comment by Unknown-0perator** [comment]
Thanks, @nam-m.
Most people don't recommend Unit Testing (UT) for the main layout. However, rendering is necessary for testing {children}. I couldn't find a better solution, so we can either ignore the warning or remove UT for the layout.

**Comment by nam-m** [comment]
> Thanks, @nam-m. Most people don't recommend Unit Testing (UT) for the main layout. However, rendering is necessary for testing {children}. I couldn't find a better solution, so we can either ignore the warning or remove UT for the layout.

Maybe we don't need unit test for the layout then. Since Next.js builds the page using `html` and `body` automatically, we can presume this will always work

**Comment by SamHuo213** [comment]
> > Thanks, @nam-m. Most people don't recommend Unit Testing (UT) for the main layout. However, rendering is necessary for testing {children}. I couldn't find a better solution, so we can either ignore the warning or remove UT for the layout.
> 
> Maybe we don't need unit test for the layout then. Since Next.js builds the page using `html` and `body` automatically, we can presume this will always work

This makes sense to me.

**Review by nam-m — APPROVED** [review]

**Pull request merged**
